# Generated by Django 5.0.6 on 2024-06-06 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccormerceApp', '0002_productmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eccormerceApp.productmodel'),
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitemmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('processing', 'processing'), ('intrasit', 'intrasit'), ('delivered', 'delivered'), ('declined', 'declined')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eccormerceApp.customermodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='orderItems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eccormerceApp.orderitemmodel'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='order_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
